# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

secondValue = 2
nextValue = 3
sumOfEvenValues = 2
locationOfValue = 4
while nextValue < 4_000_000:
    temp = nextValue
    nextValue = nextValue + secondValue
    if nextValue % 2 == 0:
        sumOfEvenValues += nextValue
    secondValue = temp
    locationOfValue += 1
print(sumOfEvenValues)
